<script type="text/javascript">
function disableEnterKey(e)
{
     var key;      
     if(window.event)
          key = window.event.keyCode; //IE
     else
          key = e.which; //firefox      

     return (key != 13);
}
</script>
<?php
/**
 * @author        Vladimir Popov
 * @copyright    Copyright (c) 2013 Vladimir Popov
 */

// in case redirect fails
if (Mage::registry('redirect_url')) {
    ?>
    <meta http-equiv="refresh" content="0;url=<?php echo Mage::registry('redirect_url') ?>">
    <script type="text/javascript">
        window.location = '<?php echo Mage::registry('redirect_url')?>';
    </script>
<?php
}
?>

<div class="contact-content">
<?php if (in_array('customer_account_create', $this->getLayout()->getUpdate()->getHandles())) { ?>
    <!-- <div class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </div> -->
<?php } ?>

<?php
// show logout message
if (Mage::helper('customer')->isLoggedIn()){
    ?>
    <p><?php echo Mage::helper('webformscrf')->__('Please <a href="%s">log out</a> of the previous session.', Mage::getUrl('customer/account/logout')) ?></p>
<?php
} else {
?>

<?php if ($this->isAjax()) { ?>
    <div id="webform_<?php echo $this->getWebform()->getId() ?>_success_text" class="std webforms-success-text"
         style="display:none"></div>
<?php } ?>

<?php
if (Mage::registry('show_success')){
    ?>
    <div class="std webforms-success-text">
        <?php echo $this->getWebform()->getSuccessText() ?>
    </div>
<?php
} else {
?>

<div id="webform_<?php echo $this->getWebform()->getId() ?>_form">

<?php if ($this->getWebform()->getDescription()) { ?>
    <div class="std">
        <?php echo $this->getWebform()->getDescription(); ?>
    </div>
<?php } ?>

<?php if ($this->isAjax()) { ?>
    <iframe id="webform_<?php echo $this->getWebform()->getId() ?>_iframe"
            name="webform_<?php echo $this->getWebform()->getId() ?>_iframe"
            style="width:0;height:0;border:0;position:absolute"></iframe>
<?php } ?>

<!-- <form action="<?php echo $this->getFormAction() ?>" method="post"
      name="webform_<?php echo $this->getWebform()->getId() ?>" id="webform_<?php echo $this->getWebform()->getId() ?>"
      enctype="<?php echo $this->getEnctype() ?>" class="webforms-<?php echo $this->getWebform()->getCode() ?>"
      <?php if ($this->isAjax()){ ?>target="webform_<?php echo $this->getWebform()->getId() ?>_iframe"<?php } ?>> -->
<form action="#<?php //echo $this->getFormAction() ?>" method="post"
      name="webform_<?php echo $this->getWebform()->getId() ?>" id="frmRegistration"
      enctype="<?php echo $this->getEnctype() ?>" class="webforms-<?php echo $this->getWebform()->getCode() ?>"
      <?php if ($this->isAjax()){ ?>target="webform_<?php echo $this->getWebform()->getId() ?>_iframe"<?php } ?>>

<input type="hidden" name="submitWebform_<?php echo $this->getWebform()->getId() ?>" value="1"/>
<input type="hidden" name="webform_id" value="<?php echo $this->getWebform()->getId() ?>"/>

<?php if (is_array($this->getData('hidden'))) {
    foreach ($this->getData('hidden') as $key => $value) {
        ?>
        <input type="hidden" name="<?php echo $key ?>" value="<?php echo $value ?>"/>
    <?php
    }
}?>

<?php if (count($this->getWebform()->_getHidden())) {
    foreach ($this->getWebform()->_getHidden() as $field) {
        echo $field->toHtml();
    }
} ?>

<!-- Default registration fields -->

    <div class="title title2">
        <span><?php echo $this->__('CREATE AN ACCOUNT') ?></span>
    </div>
    <div class="clearfix">&nbsp;</div>
    <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>"/>
    <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>"/>
    <?php //echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>            
     	<?php
		$var_attrs = array(); // will be used in JS
		$model = 'customer/attribute_collection'; 
		$type='customer'; 
		$collection = Mage::getResourceModel($model)  
		->setEntityTypeFilter( Mage::getModel('eav/entity')->setType($type)->getTypeId() )  
		->addVisibleFilter()
		->addFieldToFilter('attribute_code', array('neq' => 'medma_avatar'))
		->addFilter('is_user_defined', 1)->setOrder('sort_order', 'ASC'); 
		
        $store_id = Mage::app()->getStore()->getId();
		foreach($collection as $attribute) {
			$attr = $attribute->toArray();

			if($attr['is_required'])
			$var_attrs[] = $attr['attribute_code'];
            $store_labels = $attribute->getStoreLabels();
            $label = $store_labels[$store_id] ? $store_labels[$store_id] : $attr['frontend_label'];
			$func = 'get'.  str_replace(' ', '',  ucwords(str_replace('_', ' ', $attr['attribute_code'])) );
			
			//echo '<label for="'. $attr['attribute_code'] .'" '. ($attr['is_required']?'class="required"><em>*</em>':'>') . $this->__( $label ) . '</label>';
			switch($attr['frontend_input']) {
				case 'text':
					echo '<div class="row"><input type="text" onkeypress="return disableEnterKey(event)"  placeholder="'.$this->__( $label ).'" name="'. $attr['attribute_code'] .'" id="'. $attr['attribute_code'] .'" value="'. $this->htmlEscape($this->getFormData()->$func()) .'" class="input-text" />';
					break;
			}
		}?>
		<input onkeypress="return disableEnterKey(event)"  type="text" placeholder="Email Address"  name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" /></div>
    <!-- <div class="clearfix-registration">
        <div class="clearfix"><input type="text" placeholder="Email Address"  name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" /></div>
    </div> -->
    <div class="row">
		<input type="password" onkeypress="return disableEnterKey(event)" placeholder="Password"  name="password" id="password" title="<?php echo $this->__('Password') ?>"/>
        <input type="password" onkeypress="return disableEnterKey(event)" placeholder="Confirm Password"  name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" />
    </div> 
    <div class="row">
    <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
    <?php if ($_dob->isEnabled()): ?>
        <?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?>
    <?php endif ?>
    <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
    <?php if ($_taxvat->isEnabled()): ?>
        <?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?>
    <?php endif ?>
    <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
    <?php if ($_gender->isEnabled()): ?>
        <?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?>
    <?php endif ?>
   	</div>
    <div class="row">
		<div class="partition country">
	    	<input type="hidden" name="create_address" value="1"/>
	    	<label for="country" class="required"><?php echo $this->__('Country:') ?></label>
	    	<span class="gender-radio"><label class="medium-shortpad"><input type="radio" name="country_value" value="SG">  <img src="<?php echo $this->getSkinUrl('images/flag.jpg');?>" alt=""></label></span>
	    	<span class="gender-radio"><label class="medium-shortpad"><input type="radio" name="country_value" value="MY"> <img src="<?php echo $this->getSkinUrl('images/flag.jpg');?>" alt=""></label></span>
	    	<span class="gender-radio" id="others"><label class="medium-shortpad"><input type="radio" name="others"> Others</label></span>
	    </div>
		<div class="partition">
			<?php $_countries = Mage::getResourceModel('directory/country_collection')->loadData()->toOptionArray(false) ?>
			<?php if (count($_countries) > 0): ?>
				<select name="country_id" id="country" class="validate-select" title="Country">
			        <option value="">Select Country</option>
			        <?php foreach($_countries as $_country): ?>
			            <option value="<?php echo $_country['value'] ?>">
			                <?php echo $_country['label'] ?>
			            </option>
			        <?php endforeach; ?>
			    </select>
			<?php endif; ?>
		</div>
	</div>   
      
    <!-- <?php if ($this->isNewsletterEnabled()): ?>
        <div class="clearfix-registration">
            <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
            <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
        </div>
    <?php endif ?>     -->


<?php if ($this->getShowAddressFields()): ?>
    <div class="fieldset">
        <input type="hidden" name="create_address" value="1"/>

        <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="company"><?php echo $this->__('Company') ?></label>

                    <div class="input-box">
                        <input type="text" name="company" id="company"
                               value="<?php echo $this->htmlEscape($this->getFormData()->getCompany()) ?>"
                               title="<?php echo $this->__('Company') ?>" class="input-text"/>
                    </div>
                </div>
                <div class="field">
                    <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>

                    <div class="input-box">
                        <input type="text" name="telephone" id="telephone"
                               value="<?php echo $this->htmlEscape($this->getFormData()->getTelephone()) ?>"
                               title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry"/>
                    </div>
                </div>
            </li>
            <li class="wide">
                <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>

                <div class="input-box">
                    <input type="text" name="street[]"
                           value="<?php echo $this->htmlEscape($this->getFormData()->getStreet(1)) ?>"
                           title="<?php echo $this->__('Street Address') ?>" id="street_1"
                           class="input-text required-entry"/>
                </div>
            </li>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" name="street[]"
                               value="<?php echo $this->htmlEscape($this->getFormData()->getStreet($_i)) ?>"
                               title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>"
                               class="input-text"/>
                    </div>
                </li>
            <?php endfor ?>

            <?php if (method_exists($this->helper('customer/address'), 'isVatAttributeVisible')) { ?>
                <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                    <li class="wide">
                        <label for="vat_id"><?php echo $this->__('VAT Number') ?></label>

                        <div class="input-box">
                            <input type="text" name="vat_id"
                                   value="<?php echo $this->escapeHtml($this->getFormData()->getVatId()) ?>"
                                   title="<?php echo $this->__('VAT Number') ?>" id="vat_id"
                                   class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>"/>
                        </div>
                    </li>
                <?php endif; ?>
            <?php } // if method exists ?>

            <li class="fields">
                <div class="field">
                    <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>

                    <div class="input-box">
                        <input type="text" name="city"
                               value="<?php echo $this->htmlEscape($this->getFormData()->getCity()) ?>"
                               title="<?php echo $this->__('City') ?>" class="input-text required-entry" id="city"/>
                    </div>
                </div>
                <div class="field">
                    <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>

                    <div class="input-box">
                        <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>"
                                class="validate-select" style="display:none;">
                            <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                            //<![CDATA[
                            $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
                        </script>
                        <input type="text" id="region" name="region"
                               value="<?php echo $this->htmlEscape($this->getRegion()) ?>"
                               title="<?php echo $this->__('State/Province') ?>" class="input-text"
                               style="display:none;"/>
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>

                    <div class="input-box">
                        <input type="text" name="postcode"
                               value="<?php echo $this->htmlEscape($this->getFormData()->getPostcode()) ?>"
                               title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip"
                               class="input-text validate-zip-international required-entry"/>
                    </div>
                </div>
                <div class="field">
                    <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>

                    <div class="input-box">
                        <?php echo $this->getCountryHtmlSelect() ?>
                    </div>
                </div>
            </li>
        </ul>
        <input type="hidden" name="default_billing" value="1"/>
        <input type="hidden" name="default_shipping" value="1"/>
    </div>
<?php endif; ?>
    	<?php
		$var_attrs = array(); // will be used in JS
		$model = 'customer/attribute_collection'; 
		$type='customer'; 
		$collection = Mage::getResourceModel($model)  
		->setEntityTypeFilter( Mage::getModel('eav/entity')->setType($type)->getTypeId() )  
		->addVisibleFilter()
		->addFieldToFilter('attribute_code', array('neq' => 'medma_avatar'))
		->addFilter('is_user_defined', 1)->setOrder('sort_order', 'ASC'); 
		
        $store_id = Mage::app()->getStore()->getId();
		foreach($collection as $attribute) {
			$attr = $attribute->toArray();

			if($attr['is_required'])
			$var_attrs[] = $attr['attribute_code'];
            $store_labels = $attribute->getStoreLabels();
            $label = $store_labels[$store_id] ? $store_labels[$store_id] : $attr['frontend_label'];
			$func = 'get'.  str_replace(' ', '',  ucwords(str_replace('_', ' ', $attr['attribute_code'])) );
			
			//echo '<label for="'. $attr['attribute_code'] .'" '. ($attr['is_required']?'class="required"><em>*</em>':'>') . $this->__( $label ) . '</label>';
			switch($attr['frontend_input']) {
				case 'select':
					echo '<div class="clearfix-bday" style="width:100%; margin-top:15px;">';
					echo '<label for="'. $attr['attribute_code'] .'" '. ($attr['is_required']?'class="required"><em>*</em>':'>') . $this->__( $label ) . '</label>';
					//echo '<select name="'. $attr['attribute_code'] .'" id="'. $attr['attribute_code'] .'"  >';
					foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
						  //echo '<option value="'.$instance['value'].'" '.  ($this->htmlEscape($this->getFormData()->$func()) == $instance['value'] ? 'selected' : '') .'>' . $instance['label'] . '</option>';
						if($instance['value'] == ''){}
						else
						{
							echo '<div class="gender-radio">';
							echo '<input type="radio" name="'.$attr['attribute_code'].'" value="'.$instance['value'].'"> '.$instance['label'];
							echo '</div>';
						}

					}
					//echo '</select>';	
					echo '</div>';					
					break;
			}
		}?>
<p class="error_msg">* There are incomplete fields</p>	
<!-- <p class="error_msg2" id="error_msg2"></p> -->
<p class="error_msg2" id="error_msg2"></p>	
<div class="border"></div>
<!-- Web-form -->

<?php
foreach (Mage::registry('fields_to_fieldsets') as $fieldset_id => $fieldset) {
    ?>

    <!-- <div class="fieldset fieldset-<?php echo $fieldset_id ?> clearfix-registration"
        <?php if (!empty($fieldset['logic_visibility']) && $fieldset['logic_visibility'] == 'hidden') echo 'style="display:none"'; ?>> -->
        <!-- <?php if (!empty($fieldset['name'])) { ?>
            <h2 class="legend"><?php echo $fieldset['name'] ?></h2>
        <?php } ?> -->

        <!-- <ul class="form-list"> -->
            <?php
            $k = 0;
            $j = 0;
            $prev = false;
            $fields_count = count($fieldset['fields']);
            foreach ($fieldset['fields'] as $field) {

                $size_class = "fields";
                $field_class = "field";
                if ($field->getSize() == 'wide') {
                    $size_class = "wide";
                    $field_class = "";
                }

                ?>
                <!-- <?php if ($j % 2 == 0 || $field->getSize() == 'wide' || $prev->getSize() == 'wide') {
                    $j = 0; ?>
                    <?php if ($k > 1) { ?></li><?php } ?>
                    <li <?php if ($size_class == 'wide') { ?>id="field_<?php echo $field->getId() ?>_row" <?php } ?>
                    class="<?php echo $size_class ?> <?php if ($size_class == 'wide') { ?>webforms-fields-row-<?php echo $field->getId() ?><?php } ?>"
                    <?php if ($size_class == 'wide' && $field->getData('logic_visibility') == 'hidden') echo 'style="display:none"'; ?>>
                <?php } ?> -->

                    <?php if ($field->getType() != 'html') { ?>
                        <!-- <label for="field_<?php echo $field->getId() ?>"
                               <?php if ($field->getRequired()){ ?>class="required"<?php } ?>>

                            <?php if ($field->getRequired()) { ?>
                                <em>*</em>
                            <?php } ?>

                            <?php echo $field->getName() ?>

                        </label> -->
                    <?php } ?>

                    <div class="row">
                        <?php echo $field->toHtml('_registration'); 
                       		// $string = preg_replace('/<ul class="list-select">/', '', $field->toHtml());
							// $li = preg_replace("/<li class='control'>/", '', $string);
							// echo preg_replace('/<label/', '<label class="small"', $li);
							//echo $li;
                        ?>
						
						<?php //var_dump($field); ?>
                        <!-- <?php if ($field->getComment()) { ?>
                            <p class="webforms-fields-comment">
                                <?php echo nl2br($field->getComment()) ?>
                            </p>
                        <?php } ?> -->
                    </div>
                <?php if ($k == $fields_count - 1) { ?>
                    </li>
                <?php } ?>
                <?php
                $k++;
                $j++;
                $prev = $field;
            }?>
        <!-- </ul> -->

<?php
} // foreach 'fields_to_fieldsets'
?>

<?php if (Mage::helper('webformscrf')->showCaptchaRegistration()) { ?>
    <div class="fieldset">
        <h2 class="legend">Captcha</h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <?php echo $this->getCaptcha()->getHTML() ?>
                </div>
            </li>
        </ul>
    </div>
<?php } ?>

<?php if (Mage::getStoreConfig('webforms/honeypot/enable')) {
    echo $this->getLayout()->createBlock(
        'core/template',
        'webform_' . $this->getWebform()->getId() . '_honeypot',
        array(
            'webform' => $this->getWebform(),
            'template' => 'webforms/scripts/honeypot.phtml',
        )
    )->toHtml();
}?>

<div class="buttons-set">
	<input id="sf_text" type="text" autocomplete="off" onkeypress="return disableEnterKey(event)" name="sf_text">
	<input type="hidden" id="isSubmitClicked" name="isSubmitClicked" value="0" />
    <!-- <button type="button" class="button submit-btn" id="webform_<?php echo $this->getWebform()->getId() ?>_submit_button"
            onclick="document.getElementById('isSubmitClicked').value=1; webform_<?php echo $this->getWebform()->getId() ?>_submit();"
            title="<?php echo $this->__('submit') ?>">
				<span>
					<span><?php echo $this->__('Submit') ?></span>
				</span>
    </button> -->
    <input type="submit" value="Register" class="button" id="webform_<?php echo $this->getWebform()->getId() ?>_submit_button"  onclick="document.getElementById('isSubmitClicked').value=1; webform_<?php echo $this->getWebform()->getId() ?>_submit();">
	<span class="please-wait" id="webform_<?php echo $this->getWebform()->getId() ?>_sending_data"
          style="display:none;">
		<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
             alt="<?php echo $this->__('Sending...') ?>" title="<?php echo $this->__('Sending...') ?>"
             class="v-middle"/><span
            id="webform_<?php echo $this->getWebform()->getId() ?>_progress_text"><?php echo $this->__('Sending...') ?></span>
	</span>
</div>

</form>

</div>

</div>

<?php echo $this->getLayout()->createBlock(
    'core/template',
    'webform_' . $this->getWebform()->getId() . '_submit_script',
    array(
        'webform' => $this->getWebform(),
        'ajax' => $this->isAjax(),
        //'template' => 'webforms/scripts/registration.phtml',
        'template' => 'webforms/scripts/registration.phtml',
    )
)->toHtml();
?>

<?php if ($this->getWebform()->getLogic())
    echo $this->getLayout()->createBlock(
        'core/template',
        'webform_' . $this->getWebform()->getId() . '_logic',
        array(
            'webform' => $this->getWebform(),
            'template' => 'webforms/scripts/logic.phtml',
        )
    )->toHtml();
?>

    <script type="text/javascript">
        //<![CDATA[
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
        //]]>
    </script>

<?php
} // if(show_success)
} // log out message
?>
<div id="popup"><img src="<?=$this->getSkinUrl('images/ajax-loader.gif');?>"></div>