<?php
$validate = '';
$options = $this->getFieldOptions();
//array for letters to numbers
$letters = array(
'1'=>'a',
'2'=>'b',
'3'=>'c',
'4'=>'d',
);
foreach($this->getFieldOptions() as $i=>$option){
	$row = ($i+1);
	$checked = false;
	if($option["checked"]){
		$checked = 'checked';
	}
	if($this->getField()->getRequired() && $i==(count($options)-1)){
		$validate = "validate-one-required-by-name";
		if($this->getField()->getData('validate_regex')){
			$validate.= ' validate-field-'.$this->getField()->getId();
		}
	}
	if(!empty($option["value"])){
		$label = $option["label"];
		if($option["image_src"]){
			$label = "<img src='{$option['image_src']}'/>";
		}
?>
	<div class="partition radio">
	<input style='float:left' type='radio' name='<?php echo $this->getFieldName()?>' id='<?php echo $this->getFieldId().$i?>' value="<?php echo htmlspecialchars($option["value"])?>" class='radio <?php echo $validate?>' <?php echo $checked?> <?php if($this->getField()->getDisabled()){?> disabled <?php } ?>/>
	<label for='<?php echo $this->getFieldId().$i?>' class='<?php echo $this->getFieldClass().$letters[$row]?>' style='<?php echo $this->getFieldStyle()?>'><?php echo $label?></label>
    </div>
    <?php 
        $tooltip = $this->getField()->getTooltip($option["value"]);
        if($tooltip){
            echo $this->getLayout()->createBlock(
                'core/template',
                'field' . $this->getField()->getId() .'_option'. $i . '_tooltip',
                array(
                    'title' => $label,
                    'tooltip' => $tooltip,
                    'template' => 'webforms/scripts/tooltip.phtml',
                )
            )->toHtml();
        }
    ?>
<?php
	}
}

?>