<style>
   #page_3,#page_6,.page_6,.page_3{display:none;}
</style>
<script type="text/javascript">
	jQuery.noConflict()
	jQuery(document).ready(function($){
		$(".settings_btn a").click(function(){
			var rel = $(this).attr("rel");
			clear();
			$("#page_"+rel).fadeIn();
			$(".page_"+rel).show();
			$(".page_6").hide();
			if(rel == 6){
				$(".page_"+rel).fadeIn();	
			}
		});
		function clear()
		{
			$(".page-no .title span").each(function(){
				$(this).hide();
			});
			
			$(".slide").each(function(){
				$(this).hide();
			});
		}
	});
</script>
<?php
/**
 * @author         Vladimir Popov
 * @copyright      Copyright (c) 2014 Vladimir Popov
 */

// in case redirect fails
if (Mage::registry('redirect_url')) {
    ?>
    <meta http-equiv="refresh" content="0;url=<?php echo Mage::registry('redirect_url') ?>">
    <script type="text/javascript">
        window.location = '<?php echo Mage::registry('redirect_url')?>';
    </script>
<?php
}

// get temporary data
$tmpData = Mage::getSingleton('core/session')->getData('webform_result_tmp_' . $this->getWebform()->getId());
$tmpResult = new Varien_Object();
if (!empty($tmpData['field']) && is_array($tmpData['field'])) {
    foreach ($tmpData['field'] as $field_id => $value) {
        $tmpResult->setData('field_' . $field_id, $value);
    }
}

if ($this->getWebform()->getIsActive() == VladimirPopov_WebForms_Model_Webforms::STATUS_DISABLED || !$this->isDirectAvailable()) {
    echo $this->getNotAvailableMessage();
} else {

    if (Mage::registry('show_form_name')) {
        ?>
        <div class="page-title">
            <h1><?php echo $this->getWebform()->getName(); ?></h1>
        </div>
    <?php } ?>

    <?php if ($this->isAjax()) { ?>
        <div id="webform_<?php echo $this->getWebform()->getId() ?>_success_text" class="std webforms-success-text"
             style="display:none"></div>
    <?php } ?>

    <?php
    if (Mage::registry('show_success')) {
        ?>
        <div class="std webforms-success-text">
            <?php echo $this->getWebform()->getSuccessText() ?>
        </div>
    <?php
    } else {
        ?>

        <div id="webform_<?php echo $this->getWebform()->getId() ?>_form" class="contact-content">

            <?php if ($this->getWebform()->getDescription()) { ?>
                <div class="std">
                	 <div class="title title2"><span>Profile settings</span></div>
                    <?php echo $this->getWebform()->getDescription(); ?>
                </div>
            <?php } ?>

            <?php if ($this->isAjax()) { ?>
                <iframe id="webform_<?php echo $this->getWebform()->getId() ?>_iframe"
                        name="webform_<?php echo $this->getWebform()->getId() ?>_iframe"
                        style="width:0;height:0;border:0;position:absolute"></iframe>
            <?php } ?>

            <form action="<?php echo $this->getFormAction() ?>" method="post"
                  name="webform_<?php echo $this->getWebform()->getId() ?>"
                  id="webform_<?php echo $this->getWebform()->getId() ?>" enctype="<?php echo $this->getEnctype() ?>"
                  class="webforms-<?php echo $this->getWebform()->getCode() ?>"
                  <?php if ($this->isAjax()) { ?>target="webform_<?php echo $this->getWebform()->getId() ?>_iframe"<?php } ?>>


                <input type="hidden" name="submitWebform_<?php echo $this->getWebform()->getId() ?>" value="1"/>
                <input type="hidden" name="webform_id" value="<?php echo $this->getWebform()->getId() ?>"/>

                <?php if (is_array($this->getData('hidden'))) {
                    foreach ($this->getData('hidden') as $key => $value) {
                        ?>
                        <input type="hidden" name="<?php echo $key ?>" value="<?php echo $value ?>"/>
                    <?php
                    }
                }?>

                <?php if (count($this->getWebform()->_getHidden())) {
                    foreach ($this->getWebform()->_getHidden() as $field) {
                        echo $field->toHtml();
                    }
                } ?>

                <?php
                foreach ($this->getWebform()->_getFieldsToFieldsets() as $fieldset_id => $fieldset) {
                    ?>
					<div class="clearfix"></div>
					<div class="page-no" >
						<div class="title">
							<span class="page_0">PAGE 1 OF 3</span>
							<span class="page_3">PAGE 2 OF 3</span>
							<span class="page_6">PAGE 3 OF 3</span>
						</div>
					</div>
					<div class="clearfix"></div>
                    <div id="fieldset_<?php echo $fieldset_id ?>" class="clearfix-registration fieldset-<?php echo $fieldset_id ?>"
                        <?php if ($fieldset['logic_visibility'] == VladimirPopov_WebForms_Model_Logic::VISIBILITY_HIDDEN) echo 'style="display:none"'; ?>>
                            <?php
                            $k = 0;
                            $j = 0;
                            $prev = false;
                            $fields_count = count($fieldset['fields']);
                            foreach ($fieldset['fields'] as $field) {
                                // set temporary value
                                $field->setData('result', $tmpResult);

                                $size_class = "fields";
                                $field_class = "field";
                                if ($field->getSize() == 'wide') {
                                    $size_class = "wide";
                                    $field_class = "";
                                }

                                ?>
                                <?php //if ($j % 3 == 0 || $field->getSize() == 'wide' || $prev->getSize() == 'wide') {
                                    // $j = 0; ?>
                                    <?php //if ($k > 1) { ?></li><?php //} ?>
                                    <!-- <li style="border:solid 1px #000;" <?php if ($size_class == 'wide') { ?>id="field_<?php echo $field->getId() ?>_row" <?php } ?>
                                    class="<?php echo $size_class ?> <?php if ($size_class == 'wide') { ?>webforms-fields-row-<?php echo $field->getId() ?><?php } ?>"
                                    <?php if ($size_class == 'wide' && $field->getData('logic_visibility') == VladimirPopov_WebForms_Model_Logic::VISIBILITY_HIDDEN) echo 'style="display:none"'; ?>> -->
                                <?php //} ?>
                                <?php          
								if ($j % 3 == 0) {
								    echo "<div class='slide' id='page_$j'>";
								  }
								$j++;
                                ?>
                                <div class="c-row" id="field_<?php echo $field->getId() ?>"
                                     class="<?php echo $field_class ?> webforms-fields-<?php echo $field->getId() ?><?php if ($field->getCode()) { ?> webforms-fields-<?php echo $field->getCode();
                                     }?>"
                                    <?php if ($field->getData('logic_visibility') == VladimirPopov_WebForms_Model_Logic::VISIBILITY_HIDDEN) echo 'style="display:none"'; ?>>

                                    <?php if ($field->getType() != 'html' && $field->getType() != 'subscribe') { ?>
                                        <h3 for="field_<?php echo $field->getId() ?>"
                                               <?php if ($field->getRequired()) { ?>class="required new-title"<?php } ?>>
                                            <?php echo $field->getName() ?>
                                            <?php 
                                                $tooltip = $field->getTooltip(); 
                                                if($tooltip){
                                                    echo $this->getLayout()->createBlock(
                                                        'core/template',
                                                        'field' . $field->getId() . '_tooltip',
                                                        array(
                                                            'title' => $field->getName(),
                                                            'tooltip' => $tooltip,
                                                            'template' => 'webforms/scripts/tooltip.phtml',
                                                        )
                                                    )->toHtml();
                                                }
                                            ?>
                                        </h3>
                                    <?php } ?>

                                    <!-- <div class="input-"> -->
                                        <?php echo $field->toHtml('_settings'); ?>
                                        <?php 
										//$string = preg_replace('/<ul class="list-select">/', '', $field->toHtml());
										//echo str_replace(array("<li class='control'>","</li>","</ul>"), '', $string);
                                        ?>

                                        <?php if ($field->getComment()) { ?>
                                            <p class="webforms-fields-comment">
                                                <?php echo nl2br($field->getComment()) ?>
                                            </p>
                                        <?php } ?>
                                    <!-- </div> -->
                                </div>
								<?php
								  if ($j % 3 == 0) {
								  		
								  	$num = ($j - 3);	
								  	//echo $j;
								  	if($num == 0)
								  	{
								  		echo '<div class="c-row">';
										echo '<div class="settings_btn next"><a href="#next" rel="'.($num+3).'">Next</a></div>';
								  		//echo '<div class="next" style="float:left;width:20%;"><a href="#" rel="'.($num+3).'">Next</a></div>';
										echo '</div>';
								  	}
									else if($num == 3) {
										echo '<div class="c-row">';
										echo '<div class="settings_btn prev"><a href="#prev" rel="'.($num-3).'">Previous</a></div>';
										echo '<div class="settings_btn next"><a href="#next" rel="'.($num+3).'">Next</a></div>';
										echo '</div>';
									}
									// else{
										// echo '<div class="next" style="float:left;width:20%;"><a href="#" rel="'.($num-3).'">Preview</a></div>';
									// }
									//echo $num;
								    echo "</div>";
								  }
								  else {
									 //	 echo $j;
									 //echo $j;
								  }
								?>
                                <!-- <div class="next_<?=$k;?>"><a href="#">NEXT</a></div> -->
                                <?php if ($k == $fields_count - 1) { ?>
                                    <!-- </li> -->
                                <?php } ?>
                                <?php
                                $k++;
                                //$j++;
                                $prev = $field;
                            } //end inside foreach?>
                        <!-- </ul> -->
                    </div> <!-- fieldset -->

                <?php
                } // foreach 'fields_to_fieldsets'
                ?>

                <?php if (Mage::registry('use_captcha')) { ?>
                    <div class="fieldset">
                        <h2 class="legend">Captcha</h2>
                        <ul class="form-list">
                            <li class="fields">
                                <div class="field">
                                    <?php echo $this->getCaptcha()->getHTML() ?>
                                </div>
                            </li>
                        </ul>
                    </div>
                <?php } ?>

                <?php if (Mage::getStoreConfig('webforms/honeypot/enable')) {
                    echo $this->getLayout()->createBlock(
                        'core/template',
                        'webform_' . $this->getWebform()->getId() . '_honeypot',
                        array(
                            'webform' => $this->getWebform(),
                            'template' => 'webforms/scripts/honeypot.phtml',
                        )
                    )->toHtml();
                }?>
   				
                <div class="c-row page_6">
                	<div class="settings_btn prev"><a href="#prev" rel="3">Previous</a></div><!-- Back button-->
                    <button type="button" class="button next"
                            id="webform_<?php echo $this->getWebform()->getId() ?>_submit_button"
                            onclick="webform_<?php echo $this->getWebform()->getId() ?>_submit()"
                            title="<?php echo $this->__('submit') ?>">
                            Submit
                    </button>
					<span class="please-wait" id="webform_<?php echo $this->getWebform()->getId() ?>_sending_data"
			              style="display:none;">
						<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
			                 alt="<?php echo $this->__('Sending...') ?>" title="<?php echo $this->__('Sending...') ?>"
			                 class="v-middle"/><span
			                id="webform_<?php echo $this->getWebform()->getId() ?>_progress_text"><?php echo $this->__('Sending...') ?></span>
					</span>
                </div>

            </form>

        </div>

        <?php echo $this->getLayout()->createBlock(
            'core/template',
            'webform_' . $this->getWebform()->getId() . '_submit_script',
            array(
                'webform' => $this->getWebform(),
                'ajax' => $this->isAjax(),
                'template' => 'webforms/scripts/submit.phtml',
            )
        )->toHtml();
        ?>

        <?php echo $this->getLayout()->createBlock(
            'core/template',
            'webform_' . $this->getWebform()->getId() . '_logic',
            array(
                'webform' => $this->getWebform(),
                'template' => 'webforms/scripts/logic.phtml',
            )
        )->toHtml();
        ?>

    <?php
    } // if(show_success)
} // is active
?>