 <div class="box-account">
                    <div class="box-head">
                        <h2><?php echo $this->__('Credit Limit')?></h2>
                    </div>
                     <div>
                     <?php  echo $this->__('Your Credit balance is  %s',$this->helper('core')->currency($this->getCustomer()->getCreditLimit(),true,false));?>
                               
                         </div>
                    
            </div>
           
