<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Points
 * @version    1.7.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<div class="title title2">
	<span>Invites</span>
</div>

<br />
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if ($this->hasInvitees()): ?>  
    <!-- <fieldset> -->      
        <table class="data-table" id="invitelist-table">
            <thead>
                <tr>
                    <th><?php echo $this->__('E-mail') ?></th>
                    <th><?php echo $this->__('Status') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->getCollection() as $item): ?>
                    <tr>
                        <td>
                            <span class="nobr"><?php echo $item->getEmail() ?></span>
                        </td>
                        <td>
                            <span class="nobr"><?php echo $item->getStatus() ?></span>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('invitelist-table')</script>            
    <!-- </fieldset> -->
<?php else: ?>
    <p><?php echo $this->__("You haven't sent any invitation yet") ?></p>
<?php endif ?>
<script type="text/javascript">
    //var contactForm = new VarienForm('aw_sendinvitation', true);
</script>
