<html> 
<head>
    <style>
        .chart_overall{
            width: 260px;
            margin: 0 auto;
        }
     
        .chart_overall .legend_wrapper_overall{
            width: 100%;
            margin-top: 5px;
        }
        .chart_overall .legend_wrapper_overall li {
            float: left;
            margin: 3px;
            width: 220px;
            height: 12px;
        }
        .chart_overall .legend_wrapper_overall ul {
            list-style: none;
            padding: 0 0 0 5px;
            margin: 0px;
        }
        .chart_overall .b1,  .legend_wrapper_overall .b1 {
            background-color: #9FD6D1;
        }
        .chart_overall .b2,  .legend_wrapper_overall .b2 {
            background-color: #FFEA84;
        }
        .chart_overall .b3,  .legend_wrapper_overall .b3 {
            background-color: #FEC9C1;
        }
        .chart_overall .b4, .legend_wrapper_overall .b4 {
            background-color: #C3EAA9;
        }
        .chart_overall .b5,  .legend_wrapper_overall .b5 {
            background-color: #FD8C86;
        }
        .chart_overall .legend_wrapper_overall span {
            display: inline-block;
            margin-right: 3px;
            font-size: 9px;
            color: #8B7A5E;
            float:left;
        }
        .chart_overall .legend {
            width: 20px;
            height: 10px;
        }
    </style>
    <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">

      // Load the Visualization API and the piechart package.
      google.load('visualization', '1.0', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows([
          ['Excellent', <?php echo $this->excellent_num_users; ?>],
          ['Very Good', <?php echo $this->verygood_num_users; ?>],
          ['Good', <?php echo $this->good_num_users; ?>],
          ['Ok', <?php echo ($this->ok_num_users==0)?0:$this->ok_num_users; ?>],
          ['Bad', <?php echo ($this->bad_num_users>=1)?$this->bad_num_users:0; ?>]
        ]);


        // Set chart options
        var options = {
                       'width':270,
                       'height':300,fontSize:['11','15'],colors: [<?php echo $this->color_set;?>],
                       legend: {position: 'bottom', textStyle: {color: '#58595B', fontSize: 12}},
                       pieSliceTextStyle:{color: '#8B7A5E'},
                       pieHole: 0.5,

                       chartArea:{ width:'600'}
        };

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('all_ranking'));
        chart.draw(data, options);
      }
    </script>

  </head>

  <body>
    <!--Div that will hold the pie chart-->
    <div id="all_ranking" ></div>
<!--    <div class="chart_overall" style="display:none;">
    <div class="legend_wrapper_overall">
		<ul>
			<li>
				<span class="legend b1"></span>
				<span class="legend_indicator"><?php //echo $excellent_num_users.'/'. $total; ?> Users thinks it's Excellent</span>
				<span class="legend_label"><?php //echo $line1_percent; ?>%</span>
			</li>
			<li >
				<span class="legend b2"></span>
				<span class="legend_indicator"><?php //echo $verygood_num_users.'/'. $total; ?> Users thinks it's Very Good</span>
				<span class="legend_label"><?php //echo $line2_percent; ?>%</span>
			</li>
			<li>
				<span class="legend b3"></span>
				<span class="legend_indicator"><?php //echo $good_num_users.'/'. $total; ?> Users thinks it's Good</span>
				<span class="legend_label"><?php //echo $line3_percent; ?>%</span>
			</li>
                       
			<li>
				<span class="legend b4"></span>
				<span class="legend_indicator"><?php //echo $ok_num_users.'/'. $total; ?> Users thinks it's Ok</span>
				<span class="legend_label"><?php //echo $line4_percent; ?>%</span>
			</li>
			<li>
				<span class="legend b5"></span>
				<span class="legend_indicator"><?php //echo $bad_num_users.'/'. $total; ?> Users thinks it's Bad</span>
				<span class="legend_label"><?php //echo $line5_percent; ?>%</span>
			</li>
			
			<div style="clear: both;">
		</ul>
	</div>
    </div>-->
  </body>
</html>