<?php
/**
 * @author        Vladimir Popov
 * @copyright    Copyright (c) 2014 Vladimir Popov
 */

   $_items = $this->items;

    (int) $yesctr = 0;
    (int) $noctr = 0;
     $default_color_set = "'#9FD6D1', '#FFEA84','#FEC9C1','#C3EAA9','#FD8C86'";
    $colorFieldset = Mage::getModel('core/session')->getData('colorFieldset');
?>





<div class="webforms-results" style="margin-left:40px;">


    <?php
    
    foreach ($_items as $result) {
     
        ?>
        <div class="webforms-results-block">
          
            <?php
            $i=0;
            $ranking_data = array();
        
            foreach (Mage::registry('fields_to_fieldsets') as $fieldset) {
                
                foreach ($fieldset['fields'] as $field) {
                   
                    $text = trim($result->getData('field_' . $field->getId()));
                    $filename = $text;
                     
                    
                     // echo $customerData->getData('dob');
                    if (strlen($text) > 0 && $field->getResultDisplay() != 'off') {
                        ?>
                        <div class="webforms-results-row"  style="float: left;
width: 170px;">
                            
<?php if (strlen($field->getResultLabel()) > 1 && $field->getResultDisplay() != 'value') { ?>
            <div class="webforms-results-label">
                <?php //echo $field->getResultLabel()  ;  
                                        $i++;
                                        ?></div>
                              
                            <?php } ?>

                            <?php switch ($field->getType()) {
                                // download link
                                case 'file':
                                    echo "<a href=" . $result->getDownloadLink($field->getId(), $filename) . ">" . $filename . "</a>";
                                    break;
                                // image thumbnail
                                case 'image':
                                    // actual path of image

                                    echo "<a href='" . $result->getDownloadLink($field->getId(), $filename) . "'><img src='" . $result->getThumbnail($field->getId(), $filename, 140) . "'/></a>";
                                       
                                               
                                    break;
                                // stars rating bar
                                case 'stars':
                                        $value = (int)$text;
                                        if (strlen($field->getResultLabel()) > 1 && $field->getResultDisplay() != 'value') { 
                                            $ranking_data[] = array('name'=>$field->getResultLabel(),'rating'=>round($value));    
                                        }
                                    $width = round(100 * $value / $field->getStarsCount()) . '%';
                               
                                    echo "<div class='stars'><ul class='stars-bar'><li class='stars-value' style='width:$width'></li></ul></div>";
                                    break;
                                // text
                                default:
                                    ?>
                                        <div class="webforms-results-text">
                                            <?php
                                            
                                            if($text==='No') 
                                            {  
                                                $noctr= $noctr +1;
                                          
                                            
                                            } 
                                            else if($text==='Yes'){ 
                                                $yesctr = $yesctr + 1;
                                            }    
                                            ?>
                                            <?php 
                                                if($text!='Yes' && $text!='No'){
                                                    echo nl2br($text);
                                                
                                                 }
                                            ?>
                                           
                                        </div>
                            <div>
                                  
                            </div>
                                    <?php break;
                            } ?>
                         
                        </div>
                    <?php
                    } // if text
                } // foreach fields
             
            } // foreach fields_to_fieldsets
            //check if efficacy is more than category color set if yes replace it with the default color set.
            $colour_set = explode("','",$colorFieldset);
            $efficacy_count = count($ranking_data);
            $coulor_count   = count($colour_set);
            if($efficacy_count>$coulor_count) $colorFieldset = $default_color_set;
         
            ?>
        </div>
    
    <div style="float:left;">
         <?php echo $this->getLayout()->createBlock('lesson05/lesson05')->setData('ranking_data',$ranking_data)->setData('color_set',$colorFieldset)->setData('num_entries',$i)->setTemplate('lesson05/view_user_chart_ranking.phtml')->toHtml(); ?>
    </div>

    <?php
    } // foreach results

?>
    <div style="clear:both;"></div>



    
</div>