<?php
class Singpost_Login_NotificationController extends Mage_Core_Controller_Front_Action {
    
    public function indexAction()
    {		
		//validate if ajax request 
		if (!empty($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest' )
		{
			 //redirect request if not login, this will not work if the ajax is requested
	    	 if(!Mage::getSingleton('customer/session')->isLoggedIn()){
				 $this->getResponse()->setBody(Mage::helper('core')->jsonEncode(array("PLEASE LOGIN!")));	
			}
			 
	    	//declare the store_id and customer_id
	    	$customer_id = Mage::getSingleton('customer/session')->getId();
			$store_id = Mage::app()->getStore()->getStoreId();
			
			//popup content	
	        $model = Mage::getModel("singpost_login/profile");
	        $data = $model->getNotification();
	
			//check if close forever
			$notif_logs = $model->getNotificationLogs($customer_id);
			
			//check login count
			$login_count = $model->getUserLogCount($customer_id,$store_id);
	
			//insert to array and response as json
			$array = array('content'=>stripcslashes($data[0]['content']),'event' =>$notif_logs,'login_count'=>$login_count['count']);
	        $this->getResponse()->setBody(Mage::helper('core')->jsonEncode($array));	
		}
		else {
			//url request send back to the redirect
			 Mage::app()->getResponse()->setRedirect(Mage::getUrl('customer/account/login'));
		}
    }
	
	public function closeAction()
	{	
		//validate user if login before submit
		if(Mage::getSingleton('customer/session')->isLoggedIn())
		{
			//get customer id and store_id 
			$customer_id = Mage::getSingleton('customer/session')->getId();
			$store_id = Mage::app()->getStore()->getStoreId();
			
			//validate which ajax call is. 1 = close forever, 0 = close	
			if($this->getRequest()->getPost('val') == 1)
			{				
				$model = Mage::getModel("singpost_login/profile");
				$data = $model->closeForever($customer_id,$store_id);
				echo $data;
			}
			elseif($this->getRequest()->getPost('val') == 0)
			{
				//close only!
				$model = Mage::getModel("singpost_login/profile");
				$data = $model->closeonce($customer_id,$store_id);
				echo $data;
			}
		}
		else 
		{
			//print error
			echo "Error: The user is not login!";
		}
	}
	
	public function logSurvey()
	{
		//template ID generated by transaction mail
		$templateId = 4;
		$emailTemplate = Mage::getModel('core/email_template')->load($templateId);
		
		$sender = array('name'  => 'user','email' => 'user@ekmedia.asia');                                
		$vars = array('customer'=>$customer);
		
		$processedTemplate = $emailTemplate->getProcessedTemplate($vars);

		$mail = Mage::getModel('core/email');
		$mail->setToName('John Customer');
		$mail->setToEmail('sam@ekmedia.asia');
		$mail->setBody($processedTemplate);
		$mail->setSubject('The Subject');
		$mail->setFromEmail('yourstore@url.com');
		$mail->setFromName("SampleStore");
		$mail->setType('html');// You can use 'html' or 'text'
		
		try {
		    $mail->send();
		    Mage::getSingleton('core/session')->addSuccess('Your request has been sent');
		    $this->_redirect('');
		}
		catch (Exception $e) {
		    Mage::getSingleton('core/session')->addError('Unable to send.');
		    $this->_redirect('');
		}
	}
	
	public function testAction()
	{
		$body = "Hi there, here is some plaintext body content";
		$mail = Mage::getModel('core/email');
		$mail->setToName('John Customer');
		$mail->setToEmail('sam@ekmedia.asia');
		$mail->setBody($body);
		$mail->setSubject('The Subject');
		$mail->setFromEmail('yourstore@url.com');
		$mail->setFromName("Your Name");
		$mail->setType('text');// You can use 'html' or 'text'
		
		try {
		    $mail->send();
		    Mage::getSingleton('core/session')->addSuccess('Your request has been sent');
		    $this->_redirect('');
		}
		catch (Exception $e) {
		    Mage::getSingleton('core/session')->addError('Unable to send.');
		    $this->_redirect('');
		}
	}
	
	// public function test2Action()
	// {
       // $model = Mage::getModel("singpost_login/survey");
       // var_dump($model->logSurvey());
	// }
	
	// public function emailAction()
	// {
		// echo Mage::helper('login')->logSurvey();
	// }// end function 
}