<?php 
/**
 * Ultimate_ordersBatches extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category   	Ultimate
 * @package		Ultimate_ordersBatches
 * @copyright  	Copyright (c) 2014
 * @license		http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Batch list template on product page
 *
 * @category	Ultimate
 * @package		Ultimate_ordersBatches
 * @author Ultimate Module Creator
 */
?>
<?php $batches = $this->getBatcheCollection();?>
<?php if ($batches->count() > 0) :?>
<div class="box-collateral box-batches box-up-sell">
	<?php foreach ($batches as $batche) : ?>
		<div class="item">
				<?php echo $batche->getBatchesNameInput();?><br />
		</div>
	<?php endforeach; ?>
</div>
<?php endif;?>