<?php
	$new = "You have a pending orders to be checkout. Click here to check your order status.";
	$pending_payment = "You have made a pending for payment in checkout. Click here to check your order status.";
	$processing = "You have made a checkout. Click here to check your order status.";
	$complete = "You have made a complete checkout. Click here to check your order status.";
	$closed = "Your checkout is closed";
	$canceled  = "You calceled your checkout";
	$on_hold = "Your orders is on hold";
	$payment_review = "Your order payment is under by review.";
?>

<div class="title title2">
	<span>Notifications</span>
</div>
<div class="clearfix"></div>
<div class="table-wrap">
	<!-- <ul class="select">
		<li>Select</li>
		<li><a href="#">All</a></li>
		<li><a href="#">One</a></li>
	</ul> -->
	<div class="clearfix"></div>
	<table class="notify">
		<thead>
			<tr>
				<th scope="col">&nbsp;</th>
				<th scope="col">Description</th>
				<th scope="col">Date</th>
				<th scope="col">&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			 <!-- <span class="text-grey"><?php echo "$dateExplode[0] $monthName $dateExplode[2]"; ?> (<?php if($timeDiff > 0)echo "$timeDiff days ago"; else echo "Today";?>)</span> -->
			<?php 
				foreach($this->getNotification() as $order){
				    //do somethin
                    $date = new DateTime($order->getCreatedAt());
					$result = $date->format('d-m-Y');
					//explode the date
					$dateExplode = explode("-", $result);
					$monthName = date("F", mktime(0, 0, 0, $dateExplode[1], 10));
               		//get the number of the days
               		$dateToday = date('d-m-Y');
					$timeDiff = abs($dateToday - $result);
				    //echo $order->getCustomerEmail();
				    // echo $order->getCreatedAt();
				    //echo $order->getId();
				    if($timeDiff <= 3){
					    echo "<tr>";
						echo "<td>&nbsp;</td>";
						switch ($order->getState()) {
							case 'new':
								echo "<td>$new</td>";
								break;
							case 'processing':
								echo "<td>$processing</td>";
								break;
							case 'pending_payment':
								echo "<td>$pending_payment</td>";
								break;
							case 'complete':
								echo "<td>$complete</td>";
								break;
							case 'closed':
								echo "<td><a href='/sales/order/view/order_id/{$order->getId()}/'>$closed</a></td>";
								break;
							case 'canceled':
								echo "<td><a href='/sales/order/view/order_id/{$order->getId()}/'>$canceled</a></td>";
								break;
							case 'holded':
								echo "<td><a href='/sales/order/view/order_id/{$order->getId()}/'>$on_hold</a></td>";
								break;
							case 'payment_review':
								echo "<td><a href='/sales/order/view/order_id/{$order->getId()}/'>$payment_review</a></td>";
								break;
							default:
								echo "<td>You have no notifications as of the moment.</td>";
								break;
						}
						echo "<td>$dateExplode[0] $monthName $dateExplode[2]</td>";
						echo "<td><a href='/sales/order/view/order_id/{$order->getId()}/' target='_blank'>View Details</a></td>";
						echo "</tr>";
					}//end of if before the switch
					else{?>
						<tr>
							<td>&nbsp;</td>
							<td>You have no notifications as of the moment.</td>
							<td>-</td>
							<td>&nbsp;</td>
						</tr>
						<?php
					}
				}?>
			<!-- <tr>
				<td>&nbsp;</td>
				<td>Click here to write your pending review(s).</td>
				<td>15 January 2014</td>
				<td><a href="#">View Details</a></td>
			</tr> -->
			<!-- <tr>
				<td><input type="checkbox" value=""></td>
				<td>Click here to write your pending review(s).</td>
				<td>15 January 2014</td>
				<td><a href="#">View Details</a></td>
			</tr> -->
  		</tbody>
	</table>
	<!-- <div class="row"><input type="submit" value="Dismiss Selected" class="submit-btn"></div> -->
</div>