<?php $info = $this->getAddress();
$customer = Mage::getModel("customer/customer")->load(Mage::getSingleton('customer/session')->getId());
?>
<div class="title title2">
	<span>SETTINGS</span>
</div>
<div class="clearfix"></div>
<div class="profile-wrap">
	<div class="profile-block profile-divide">
		<h4 class="edit-pic">Password<a class="edit_pop" title="Custom effect" href="#modal-5" data-custombox="1404897487">Edit</a></h4>
		<h5>Change new Password</h5>
	</div>
	<div class="profile-block profile-divide">
		<h4 class="edit-pic">Mobile No. <a class="edit_pop" title="Custom effect" href="#modal-6" data-custombox="1404897457">Edit</a></h4>
		<!-- <h5>9876 5432 (Verified <i class="fa fa-check"></i>)</h5> -->
		<h5><?=$info['telephone'];?></h5>
	</div>
	<div class="profile-block profile-divide">
		<h4 class="edit-pic">Email <a href="#modal-7" class="edit_pop" title="Custom effect">Edit</a></h4>
		<h5><?=$customer->getEmail();?></h5>
	</div>
	<div class="profile-block profile-divide">
		<h4 class="edit-pic">Country <a href="#modal-8" class="edit_pop" title="Custom effect">Edit</a></h4>
		<h5><img src="<?=$this->getSkinUrl('images/flag.jpg');?>" alt=""> 
			<?php
			$collection = Mage::getModel('directory/country')->getCollection();   
		    foreach ($collection as $country)
		    {
				if($info['country_id'] ==  $country->getId()){
					echo $country->getName();	
				}
		    }?>
		</h5>
	</div>
	<div class="profile-block profile-divide">
		<h4 class="edit-pic">Shipping Address <a href="#modal-9" class="edit_pop" title="Custom effect">Edit</a></h4>
		<h5><?php if(!empty($info['shipping_address']))echo $info['shipping_address']; else{}?></h5>
	</div>
	<div class="profile-block profile-divide">
		<h4 class="edit-pic">Newsletter Subscription <a href="#modal-10" class="edit_pop" title="Custom effect">Edit</a></h4>
		<h5>Receive up to date new product <br>information and special offers <br>from The Sample Store.</h5>
	</div>
</div>

<div id="modal-5" style="display: none;" class="modal-example-content modal-example-content-md">
  <div class="modal-example-header modal-example-header-white">
    <button type="button" class="close close-white" >Close <span>&times;</span></button>
  </div>
  <div class="message"></div>
  <div class="modal-example-body modal-example-body-md">
    <div class="title title2 move-20"><span>Change Password</span></div>
    <div id="error_msg"></div>
    <div class="login-block">
      <div class="form">
        <form method="post" action="" id="frmPassword" name="frmPassword">
          <div class="row">
            <input type="password" placeholder="Current Password" name="current_password" id="current_password">
          </div>
          <div class="row">
            <input type="password" placeholder="New Password" name="new_password" id="new_password">
          </div>
          <div class="row">
            <input type="password" placeholder="ReType New Password" name="confirm_password" id="confirm_password">
          </div>
          <div class="row">
          	<!-- <input type="submit" class="confirm" value="Confirm" id="confirm"> -->
          	<input type="submit" value="Confirm" id="updatePassword" class="submit-btn">
            <!-- <input type="submit" class="confirm" value="Confirm" id="confirm" class="submit-btn"> -->
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<div id="modal-6" style="display: none;" class="modal-example-content modal-example-content-md">
	<div class="modal-example-header modal-example-header-white">
		<button type="button" class="close close-white" >Close <span>&times;</span></button>
 	</div>
	<div class="modal-example-body modal-example-body-md">
		<div class="title title2 move-20"><span>Change Mobile Number</span></div>
		<div id="error_msg"></div>
		<div class="login-block">
			<div class="form">
				<form method="post" id="frmMobile" name="frmMobile">
				<div class="row"><input type="text" placeholder="New Mobile No." name="mobile_num" id="mobile_num"><!-- <input type="email" value="" placeholder="Enter SMS PIN"> --></div>
				<div class="row">
					<div class="p-small"><p>An SMS with the OTP has been sent to your phone number (last 4-digits 5432).</p></div>
				</div>
				<div class="row"><input type="submit" value="Confirm" id="updateMobile" class="submit-btn"><!-- <input type="submit" value="Confirm" class="submit-btn"> --></div>
				</form>
			</div>
		</div>
	</div>
</div>

<div id="modal-7" style="display: none;" class="modal-example-content modal-example-content-md">
	<div class="modal-example-header modal-example-header-white">
		<button type="button" class="close close-white" >Close <span>&times;</span></button>
	</div>
<div class="modal-example-body modal-example-body-md">
	<div class="title title2 move-20"><span>Change Email</span></div>
	<div id="error_msg"></div>
	<div class="login-block">
		<div class="form">
			<form method="post" id="frmEmail" name="frmEmail">
			<div class="row">
				<input type="text" placeholder="New Email" name="email_address" id="email_address">
				<!-- <p class="error text-align-right">Incomplete field</p> -->
			</div>
			<div class="row">
				<input type="password" placeholder="Password" name="user_password" id="user_password">
			</div>
			<div class="row">
				<div class="p-small"><p>Your current email address is <strong><?=$customer->getEmail();?>.</strong> 
				You can change your email address above. 
				Your current password is required for security reasons.</p></div>
			</div>
			<div class="row"><input type="submit" value="Confirm" id="updateEmail" class="submit-btn"><!-- <input type="submit" value="Confirm" class="submit-btn"> --></div>
			</form>
		</div>
	</div>
</div>
</div>

<div id="modal-8" style="display: none;" class="modal-example-content modal-example-content-md">
	<div class="message"></div>
	<div class="modal-example-header modal-example-header-white">
		<button type="button" class="close close-white" >Close <span>&times;</span></button>
	</div>
	<div class="modal-example-body modal-example-body-md">
		<div class="title title2 move-20"><span>Change country</span></div>
		<div id="error_msg"></div>
		<div class="clearfix"></div>
		<form method="post" id="frmCountry" name="frmCountry">
		<div class="login-block">
			<div class="row">
				<label class="width-55">Country</label>
				<label class="medium"><input type="radio" name="country_value" value="SG"><img src="<?=$this->getSkinUrl('images/flag.jpg');?>" alt=""></label>
				<label class="medium"><input type="radio" name="country_value" value="MY"> <img src="<?=$this->getSkinUrl('images/flag.jpg');?>" alt=""></label>
				<label class="medium"><input type="radio" id="others"> Others</label>
			</div>
			<div class="row">
				<div id="country_dropdown" style="display:none;">
					<?php $_countries = Mage::getResourceModel('directory/country_collection')->loadData()->toOptionArray(false) ?>
					<?php if (count($_countries) > 0): ?>
					    <select name="country" id="country">
					        <option value="">Select Country</option>
					        <?php foreach($_countries as $_country): ?>
					            <option value="<?php echo $_country['value'] ?>">
					                <?php echo $_country['label'] ?>
					            </option>
					        <?php endforeach; ?>
					    </select>
					<?php endif; ?>
				</div>
			</div>
			<div class="row">
				<input type="submit" value="Confirm" id="updateCountry" class="submit-btn"><!-- <input type="submit" value="Confirm" class="submit-btn"> -->
			</div>
		</div>
		</form>
	</div>
</div>
	<!-- <div id="profile">
		<div class="preference">
			<h3>SETTINGS</h3>
			<div class="pref_content">
				<p class="title">Password <span class="edit"><a href="#changePassword">Edit</a></span></p>
				<p>Change new password</p>
			</div>
			<div class="pref_content">
				<p class="title">Mobile No. <span class="edit"><a href="#mobile">Edit</a></span></p>
				<p>9876 5432</p>
			</div>	
			<div class="pref_content">
				<p class="title">Email <span class="edit"><a href="#email">Edit</a></span></p>
				<p>sam@ekmedia.asia</p>
			</div>	
			<div class="pref_content">
				<p class="title">Country <span class="edit"><a href="#countrySettings">Edit</a></span></p>
				<p>Singapore</p>
			</div>
			<div class="pref_content">
				<p class="title">Shipping Address <span class="edit"><a href="#address">Edit</a></span></p>
				<p>14 toa payo...</p>
			</div>
			<div class="pref_content">
				<p class="title">Newsletter Subscription <span class="edit"><a href="#newsletter">Edit</a></span></p>
				<p>Receive up to date new product information and special offers from The Sample Store.</p>
			</div>				
		</div>
	</div>
	
<div id="changePassword">
	<div class="message"></div>
	<form method="post" action="" id="frmPassword" name="frmPassword">
		<div class="clearfix">
			<h3>&#151;&#151;&#151;&#151; CHANGE PASSWORD &#151;&#151;&#151;&#151;</h3>
		</div>
		<div class="clearfix">
			<input type="password" placeholder="Current Password" name="current_password" id="current_password">
		</div>
		<div class="clearfix">
			<input type="password" placeholder="New Password" name="new_password" id="new_password">
		</div>
		<div class="clearfix">
			<input type="password" placeholder="ReType New Password" name="confirm_password" id="confirm_password">
		</div>
		<div class="clearfix">
			<input type="submit" class="confirm" value="Confirm" id="confirm">
		</div>
	</form>
</div> -->

<!-- <div id="email">
	<div class="message"></div>
	<form method="post" id="frmEmail" name="frmEmail">
		<div class="clearfix">
			<h3>&#151;&#151;&#151;&#151; CHANGE EMAIL &#151;&#151;&#151;&#151;</h3>
		</div>
		<div class="clearfix">
			<input type="text" placeholder="New Email" name="email_address" id="email_address">
		</div>
		<div class="clearfix">
			<input type="password" placeholder="Password" name="user_password" id="user_password">
		</div>
		<div class="clearfix">
			<input type="submit" class="confirm" value="Confirm" id="confirm">
		</div>
	</form>
</div> -->

<!-- <div id="mobile">
	<div class="message"></div>
	<form method="post" id="frmMobile" name="frmMobile">
		<div class="clearfix">
			<h3>&#151;&#151;&#151;&#151; CHANGE MOBILE NO &#151;&#151;&#151;&#151;</h3>
		</div>
		<div class="clearfix">
			<input type="text" placeholder="New Mobile No." name="mobile_num" id="mobile_num">
		</div>
		<div class="clearfix">
			<input type="submit" class="confirm" value="Confirm" id="confirm">
		</div>
	</form>
</div> -->

<!-- <div id="countrySettings">
	<div class="message"></div>
	<form method="post" id="frmCountry" name="frmCountry">
		<div class="clearfix">
			<h3>&#151;&#151;&#151;&#151; CHANGE COUNTRY&#151;&#151;&#151;&#151;</h3>
		</div>
		<div class="clearfix">
			<input type="radio" name="country_value" value="SG"> Singapore
			<input type="radio" name="country_value" value="MY"> Malaysia
			<input type="radio" id="others"> Others
		</div>
		<div id="country_dropdown" style="display:none;">
			<?php $_countries = Mage::getResourceModel('directory/country_collection')->loadData()->toOptionArray(false) ?>
			<?php if (count($_countries) > 0): ?>
			    <select name="country" id="country">
			        <option value="">Select Country</option>
			        <?php foreach($_countries as $_country): ?>
			            <option value="<?php echo $_country['value'] ?>">
			                <?php echo $_country['label'] ?>
			            </option>
			        <?php endforeach; ?>
			    </select>
			<?php endif; ?>
		</div>
		<div class="clearfix">
			<input type="submit" class="confirm country_confirm" value="Confirm" id="confirm">
		</div>
	</form>
</div> -->

<div id="modal-9" style="display: none;" class="modal-example-content modal-example-content-md">
	<div class="modal-example-header modal-example-header-white">
    	<button type="button" class="close close-white" >Close <span>&times;</span></button>
  	</div>
  	<div class="modal-example-body modal-example-body-md">
    	<div class="title title2 move-20"><span>Shipping Address</span></div>
    	<div id="error_msg"></div>
	    <div class="login-block">
			<div class="form">
		        <form method="post" id="frmShipping" name="frmShipping">
				<!-- <div class="row">
		        	<div class="p-small"><p>Confirm to add the new shipping address</p></div>
		        </div> -->
				<div class="row">
					<input type="text" placeholder="Shipping Address" name="shipping_address" id="shipping_address">
				</div>
				<!-- <div class="row">
		        	<div class="p-small"><p><a href="#">It’s incorrect. I want to edit it.</a></p></div>
		        </div> -->
				<div class="row">
					<input type="submit" value="Confirm" id="updateShipping" class="submit-btn">
					<!-- <input type="submit" value="Confirm" class="submit-btn"> -->
				</div>
		        </form>
	      </div>
	    </div>
  	</div>
</div>

<div id="modal-10" style="display: none;" class="modal-example-content modal-example-content-md">
  	<div class="modal-example-header modal-example-header-white">
    	<button type="button" class="close close-white" >Close <span>&times;</span></button>
 	 </div>
  	<div class="modal-example-body modal-example-body-md">
	<div class="title title2 move-20"><span>Newsletter subscription</span></div>
	<div id="error_msg"></div>
	<div class="login-block form-mid">
  		<div class="form">
  		<?php 
  		//print_r($this->getUserNewsletter());
		//exit;
  		?>
		<form method="post" id="frmShipping" name="frmShipping">
			<?php $newsLetter = $this->getNewsletter();?>
			<?php $userNewsLetter = $this->getUserNewsletter();?>
			<?php for($i= 0; $i<count($this->getNewsletter()); $i++):?>
				<?php //echo $newsLetter[$i]['value'];?>
				<?php 
				//echo $userNewsLetter[$i]['code'];
				?>
				<div class="row">
					<input type="checkbox" name="<?php if($newsLetter[$i]['code'] == 'special_offers')echo 'special_offers'; else if($newsLetter[$i]['code'] == 'new_product_information') echo 'new_product_info'; ?>" 
						id="<?php if($newsLetter[$i]['code'] == 'special_offers')echo 'special_offers'; else if($newsLetter[$i]['code'] == 'new_product_information') echo 'new_product_info'; ?>" 
						value="1" <?=$userNewsLetter[1]['code']?>
						<?php if($userNewsLetter !== false){
							//check if the user have check the news letter
							 //if($userNewsLetter[$i]['value'] == ''){}
							// else if($userNewsLetter[$i]['code'] == 'special_offers') echo "checked";
							if($userNewsLetter[1]['code'] == 'terms_and_condition'){}
							else if($userNewsLetter[1]['code'] == 'special_offers' && $userNewsLetter[1]['value'] != '') echo "checked";
							else if($userNewsLetter[2]['code'] == 'new_product_information' && $userNewsLetter[1]['value'] != '')echo "checked";
							//elseif($userNewsLetter[$i]['code'] == 'new_product_information') echo "checked";
						}?>>
					<label class="small">
						<?=$newsLetter[$i]['value']?>
					</label>
				</div>
			<?php endfor;?>
			<div class="row">
				<input type="hidden" id="result_id" name="result_id" value="<?=$userNewsLetter[0]['result_id']?>">
				<input type="button" class="submit-btn" value="Confirm" id="updateNewsletter">
			</div>
		</form>
  		</div>
	</div>
  	</div>
</div>
<div id="popup"><img src="<?=$this->getSkinUrl('images/ajax-loader.gif');?>"></div>
<script src="<?= $this->getJsUrl('singpost/method/easytabs.js');?>"></script> 
<script src="<?= $this->getJsUrl('singpost/method/jquery.custombox.js');?>"></script> 
<script src="<?= $this->getJsUrl('singpost/method/jquery-filestyle.min.js');?>"></script> 
<script src="<?= $this->getJsUrl('singpost/method/unslider.min.js');?>"></script>
<script src="<?= $this->getJsUrl('singpost/method/main.js');?>"></script> 