<?php
/**
 * SilverTouch Technologies Limited.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.silvertouch.com/MagentoExtensions/LICENSE.txt
 *
 * @category   Sttl
 * @package    Sttl_Silverbrand
 * @copyright  Copyright (c) 2011 SilverTouch Technologies Limited. (http://www.silvertouch.com/MagentoExtensions)
 * @license    http://www.silvertouch.com/MagentoExtensions/LICENSE.txt
 */
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    /*if ($_imgUrl = $_category->getImageUrl()) {
		echo $_category->getImageUrl();
		echo '<br>';
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }*/
	
	if ($_imgUrl = $_category->getThumbnail()) {
		$_thumbnailImgageName	=	$_category->getThumbnail();
		$_thumbnailImgageUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/category/'.$_thumbnailImgageName;
                $_imgHtml = '<img class="silverBrandViewLogo" src="'.$_thumbnailImgageUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" />';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'thumbnail');
    }
?> 

<div class="page-title category-title">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
   
</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="silverBrandViewPage">
	<div class="silverBrandViewImage">
		<?php if($_imgUrl): ?>
			<?php echo $_imgHtml ?>
		<?php endif; ?>
	</div>
	<div class="silverBrandViewDes">
		<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
		<div class="category-description std">
			<?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
		</div>
		<?php endif; ?>
	</div>
</div>

<div style="clear:both;"></div>


<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
